Attempt to fix CircleCI
The `brew install` step is failing because:

  Error: libffi 3.0.13 is already installed
  To upgrade to 3.2.1, run `brew upgrade libffi`

This patch removes `libffi` from the list.

Signed-off-by: David Scott <dave.scott@docker.com>