Work around build failure in uri package
The failure looks like:
```
ocamlc lib/.uri.objs/byte/uri_re.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.uri.objs/byte -no-alias-deps -o lib/.uri.objs/byte/uri_re.cmo -c -impl lib/.wrapped_compat/Uri_re.ml-gen)
File "lib/.wrapped_compat/Uri_re.ml-gen", line 1, characters 99-110:
Error: Unbound module Uri__Uri_re
```

I suspect it's due to a missed dependency within the code itself, probably
due to the old packages and `dune`/`jbuilder` version. Building the package
separately seems to hide the problem, which is enough until we can upgrade
a lot of the dependencies.

Signed-off-by: David Scott <dave@recoil.org>